### ISSUE TITLE
Clean make hangs until I manually close matplotlib images

### ISSUE THREAD

**Issue by scopatz** [ergs/transmutagen-paper#3]
On my machine, matplotlib will popup with a new window when I run make. This will hang at the following location, until I manually close the popup.  It seems to me that make should execute without human interaction.

```console
scopatz@artemis ~/transmutagen-paper master $ env TRANSMUTAGEN_DATA=~/transmutagen-data TRANSMUTAGEN=~/transmutagen/transmutagen/tests make
python -m transmutagen.analysis --eigenvals --no-title --file eigenvals.pdf --pwru50-data=/home/scopatz/transmutagen/transmutagen/tests/data/pwru50_400000000000000.0.npz
analyzing eigenvalues of pwru50
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
<HANG>
analyzing eigenvalues of decay
```

**Comment by asmeurer** [comment]
Sorry. I think my iterm2 stuff takes a different code path.

**Comment by scopatz** [comment]
Now worries, I figured it was something like this.  If you could put in a fix that would be great!

**Comment by asmeurer** [comment]
OK, pull transmutagen and let me know if you still get plots.

**Comment by scopatz** [comment]
Ok! I don't seem to get any plots.  Thanks!

**Comment by scopatz** [comment]
Actually it still seems to be producing plot windows right before the following section:

```
Off by:  			4.7943e-20 
Our error is better
python generate_convergence_plot.py
python cram_plot.py
python error_plot.py
```

**Comment by asmeurer** [comment]
Sorry I forgot about this one. I am not able to reproduce this. Can you double check that you have pulled the latest transmutagen and transmutagen-paper? What is the plot that pops up?

**Comment by scopatz** [comment]
I guess it doesn't hang.  It pops up a plot window, continues on without rendering anything and then closes. I don't know that this is a deal breaker then, though such behaviour might fail in headless mode.

**Comment by asmeurer** [comment]
In my experience matplotlib generally fails in headless mode anyway, unless you create an rc file that switches the backend. 

It would be nice to fix this, but without being able to reproduce it or at least knowing which file is causing it I don't know what to do.

**Comment by scopatz** [comment]
Yeah, I agree. I don't think it is a priority.  I only know that the figure pops up at the position in the build mentioned above
